<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Company>Kaching</Company>
    <Product>Kaching Windows</Product>
    <Authors>Kaching</Authors>
  </PropertyGroup>
</Project>
